# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'emb.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Embroidery(object):
    def setupUi(self, Embroidery):
        Embroidery.setObjectName("Embroidery")
        Embroidery.setEnabled(True)
        Embroidery.resize(174, 82)
        self.centralwidget = QtWidgets.QWidget(Embroidery)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        Embroidery.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Embroidery)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 174, 21))
        self.menubar.setObjectName("menubar")
        Embroidery.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Embroidery)
        self.statusbar.setObjectName("statusbar")
        Embroidery.setStatusBar(self.statusbar)

        self.retranslateUi(Embroidery)
        QtCore.QMetaObject.connectSlotsByName(Embroidery)

    def retranslateUi(self, Embroidery):
        _translate = QtCore.QCoreApplication.translate
        Embroidery.setWindowTitle(_translate("Embroidery", "MainWindow"))
        self.pushButton_2.setText(_translate("Embroidery", "Floriani"))
        self.pushButton.setText(_translate("Embroidery", "Wilcom"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Embroidery = QtWidgets.QMainWindow()
    ui = Ui_Embroidery()
    ui.setupUi(Embroidery)
    Embroidery.show()
    sys.exit(app.exec_())
